name: AetherVPN
main: com.icebergcraft.aethervpn.Main
description: Block players from using VPNs on your server!
author: Johnanater
version: 1.0.0.0
softdepend: [PermissionsEx, Permissions]
commands:
    aethervpn:
        description: Show plugin info
        usage: /aethervpn [<enable/disable/clearcache>]
    playerinfo:
        description: Lookup a player's IP info
        usage: /playerinfo <player>
    lookup:
        description: Lookup an IP's info
        usage: /lookup <ip>
    plugins:
        description: e
        usage: e
